{% set name = "promis" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/vlachosg37/promis/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6cfbc73bf767dace39a095135dafd09cf2f4ed007d2b59e760be413521694d28


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=64
    - pandas >=1.5
    - numpy >=1.23
    - scikit-learn >=1.1
    - matplotlib-base >=3.5
    - seaborn >=0.11
    - pysam >=0.21
    - pyyaml >=5.4
    - rich >=13
    - tqdm >=4.64
    - numba >=0.57
    - snakemake >=9.9.0
  run:
    - python >=3.10
    - pandas >=1.5
    - numpy >=1.23
    - scikit-learn >=1.1
    - matplotlib-base >=3.5
    - seaborn >=0.11
    - pysam >=0.21
    - pyyaml >=5.4
    - rich >=13
    - tqdm >=4.64
    - numba >=0.57
    - snakemake >=9.9.0


test:
  commands:
    - promis --help
    - promis --print-config > /dev/null
    - promis --workflow-dir > /dev/null
    - promis-find-ms-sites --help

about:
  home: https://github.com/vlachosg37/promis
  summary: Snakemake pipeline for microsatellite instability analysis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vlachosg37
  channels:
    - conda-forge
    - bioconda
    - defaults

